import { defineDocs, defineConfig } from "fumadocs-mdx/config";

const docs = { postprocess: { includeProcessedMarkdown: true } };

// core and alineo are versioned (see plans/versioned-docs.md). fumadocs-mdx requires
// every export here to itself be a defineDocs() collection (it rejects a nested
// object/map — "Unknown export, you can only export collections"), and ES module
// export names must be static text, so a *variable* number of versions can't be a
// plain runtime loop over this file's exports. The block below is instead
// regenerated by scripts/sync-doc-versions.ts (predev/prebuild) from whatever
// content/docs/<product>/vX.Y/ folders exist on disk — don't hand-edit inside the
// markers; add/remove a content folder and re-run `bun run build` (or just commit —
// CI's Build step runs prebuild too) instead. Never rename/remove an existing
// version's dir — it's a frozen snapshot older installs' docs point at.
// AUTO-GENERATED-VERSIONED-DOCS:START
export const coreV01Docs = defineDocs({ dir: "content/docs/core/v0.1", docs });
export const coreV02Docs = defineDocs({ dir: "content/docs/core/v0.2", docs });
export const coreV03Docs = defineDocs({ dir: "content/docs/core/v0.3", docs });
export const alineoV01Docs = defineDocs({ dir: "content/docs/alineo/v0.1", docs });
export const alineoV02Docs = defineDocs({ dir: "content/docs/alineo/v0.2", docs });
export const alineoV03Docs = defineDocs({ dir: "content/docs/alineo/v0.3", docs });
// AUTO-GENERATED-VERSIONED-DOCS:END

export const workflowDocs = defineDocs({ dir: "content/docs/workflow", docs });
export const agentDocs = defineDocs({ dir: "content/docs/agent", docs });
export const examplesDocs = defineDocs({ dir: "content/docs/examples", docs });
export const cookbooksDocs = defineDocs({ dir: "content/docs/cookbooks", docs });

export default defineConfig();
