/**
 * The published OpenAPI document is read by agents that turn it into function-calling tools:
 * the operationId becomes the tool name, the description its prompt. Both must exist on every
 * operation, and ids must be unique. `spec/openapi.json` is generated by `bun run spec`.
 */
import { describe, expect, test } from "bun:test";
import spec from "../spec/openapi.json";

type Op = { operationId?: string; description?: string; summary?: string };
const ops = Object.entries(spec.paths).flatMap(([path, item]) =>
  Object.entries(item as Record<string, Op>).map(([method, op]) => ({
    key: `${method.toUpperCase()} ${path}`,
    op,
  })),
);

describe("spec/openapi.json", () => {
  test("is OpenAPI 3.1 with a self-hosted server entry", () => {
    expect(spec.openapi).toBe("3.1.0");
    expect(spec.servers[0]?.url).toContain("localhost");
  });

  test("every operation has an operationId", () => {
    expect(ops.filter(({ op }) => !op.operationId).map((o) => o.key)).toEqual([]);
  });

  test("operationIds are unique and camelCase", () => {
    const ids = ops.map(({ op }) => op.operationId!);
    expect(new Set(ids).size).toBe(ids.length);
    for (const id of ids) expect(id).toMatch(/^[a-z][A-Za-z0-9]*$/);
  });

  test("every operation has a description longer than its summary", () => {
    for (const { key, op } of ops) {
      expect(op.description, key).toBeDefined();
      expect(op.description!.length, key).toBeGreaterThan((op.summary ?? "").length);
    }
  });
});
