#!/usr/bin/env bun
import { writeFileSync } from "node:fs";
import path from "node:path";
import { discoverVersions, urlVersion } from "./doc-versions";

// Regenerates public/_redirects from whatever content/docs/<product>/vX.Y/ folders
// actually exist on disk. Cloudflare Pages reads that file as static text, not
// through the Next.js build (output: "export" can't use next.config.ts's
// redirects()), so without this it's the one part of a version cut that's easy to
// forget — see plans/versioned-docs.md. Run via predev/prebuild (package.json), so
// it's always current before `next dev`/`next build` reads it... except it doesn't
// read it either; Cloudflare does, at deploy time, so this just keeps the checked-in
// file honest between commits.
const OUT = path.join(import.meta.dirname, "..", "public", "_redirects");

function block(product: "core" | "alineo") {
  const versions = discoverVersions(product);
  const latestFolder = versions.at(-1);
  if (!latestFolder) throw new Error(`No "vX.Y" version folders found for ${product}`);
  const latest = urlVersion(latestFolder);
  const passthroughs = versions
    .map((v) => urlVersion(v))
    .map(
      (v) =>
        `/docs/${product}/${v}          /docs/${product}/${v}               200\n` +
        `/docs/${product}/${v}/*      /docs/${product}/${v}/:splat        200`,
    )
    .join("\n");
  const redirects =
    `/docs/${product}             /docs/${product}/${latest}               301\n` +
    `/docs/${product}/*            /docs/${product}/${latest}/:splat        301`;
  return { passthroughs, redirects, latest };
}

const core = block("core");
const alineo = block("alineo");

const content = `# Cloudflare Pages redirects (see plans/versioned-docs.md). apps/docs is a static
# export (output: "export"), so these can't live in next.config.ts's redirects() —
# that API is unsupported for static export. Cloudflare Pages reads this file at
# the edge instead, ahead of Next's own routing, so it covers old/external links to
# the pre-versioning unversioned /docs/core and /docs/alineo URLs (already indexed
# in production before this change) that in-app links no longer generate themselves.
#
# GENERATED by scripts/sync-redirects.ts (predev/prebuild) from whatever
# content/docs/<product>/vX.Y/ folders exist on disk — don't hand-edit the version
# numbers below; add/remove a content folder and re-run \`bun run build\` (or just
# commit — CI's Build step runs prebuild too) instead.
#
# Rules are evaluated top-to-bottom, first match wins. The 200-status rules below
# are passthroughs, not redirects — without them the /docs/core/* wildcard further
# down would also match already-versioned paths like /docs/core/0.1/getting-started
# and double-prefix them into /docs/core/0.1/0.1/getting-started.
#
# The bare "/docs/core/0.1" (no trailing segment) needs its own exact-match
# passthrough line — "/docs/core/0.1/*" only matches paths with something *after*
# the trailing slash, not the version root itself. Without this, "/" 's client-side
# redirect() to "/docs/core/0.1" falls through to the "/docs/core/*" 301 below and
# gets double-prefixed into "/docs/core/0.1/0.1", which 404s.
${core.passthroughs}
${alineo.passthroughs}

# Legacy "vX.Y"-prefixed URLs — every version folder was named e.g. "v0.1" and the
# URL matched it exactly (/docs/core/v0.1/...) until the "v" was dropped from the
# *URL* (folders/defineDocs()/CHANGELOG-style names keep it). /docs/core/v0.1 was
# live and indexed in production before that change, so it needs a permanent
# redirect to the same content's new address — not just the versions still on
# disk, so this list is hand-maintained here rather than derived from
# discoverVersions() like everything else in this file. Must come before the
# "redirect unversioned alias to latest" block below — that block's /docs/core/*
# wildcard would otherwise swallow /docs/core/v0.1/* first and double-prefix it.
/docs/core/v0.1               /docs/core/0.1                301
/docs/core/v0.1/*              /docs/core/0.1/:splat         301
/docs/alineo/v0.1              /docs/alineo/0.1               301
/docs/alineo/v0.1/*             /docs/alineo/0.1/:splat        301

${core.redirects}
${alineo.redirects}

# Handled here rather than left to src/app/page.tsx's redirect() call: static export
# can't perform a real server redirect for "/", so Next instead bakes the page as an
# error-boundary shell ("This page could not be found") that a client-side script is
# supposed to replace via router.replace() after hydration — fragile (a no-JS client
# or crawler sees the 404 shell as the actual response) and, before this rule existed,
# actively broken (that client-side nav re-entered the rules above and got
# double-prefixed into /docs/core/0.1/0.1). An edge-level 301 sidesteps all of it.
/                      /docs/core/${core.latest}               301
`;

writeFileSync(OUT, content);
console.log(`[sync-redirects] wrote ${path.relative(process.cwd(), OUT)} — core latest=${core.latest}, alineo latest=${alineo.latest}`);
