import {
  coreV01Docs,
  coreV02Docs,
  alineoV01Docs,
  alineoV02Docs,
  workflowDocs,
  agentDocs,
  examplesDocs,
  cookbooksDocs,
} from "collections/server";
import { loader } from "fumadocs-core/source";

// core and alineo are versioned (see plans/versioned-docs.md). Each entry is a
// fully independent loader() over a frozen content dir — cutting a new version
// never touches an older one. The block below (imports above included) is
// regenerated by scripts/sync-doc-versions.ts (predev/prebuild) from whatever
// content/docs/<product>/vX.Y/ folders exist on disk — don't hand-edit inside the
// markers, see source.config.ts's own comment for why.
// AUTO-GENERATED-VERSIONED-DOCS:START
export const coreVersions = {
  "0.1": loader({ baseUrl: "/docs/core/0.1", source: coreV01Docs.toFumadocsSource() }),
  "0.2": loader({ baseUrl: "/docs/core/0.2", source: coreV02Docs.toFumadocsSource() }),
} as const;
export const coreLatestVersion: keyof typeof coreVersions = "0.2";
export const coreSource = coreVersions[coreLatestVersion];

export const alineoVersions = {
  "0.1": loader({ baseUrl: "/docs/alineo/0.1", source: alineoV01Docs.toFumadocsSource() }),
  "0.2": loader({ baseUrl: "/docs/alineo/0.2", source: alineoV02Docs.toFumadocsSource() }),
} as const;
export const alineoLatestVersion: keyof typeof alineoVersions = "0.2";
export const alineoSource = alineoVersions[alineoLatestVersion];
// AUTO-GENERATED-VERSIONED-DOCS:END

export const workflowSource = loader({
  baseUrl: "/docs/workflow",
  source: workflowDocs.toFumadocsSource(),
});

export const agentSource = loader({
  baseUrl: "/docs/agent",
  source: agentDocs.toFumadocsSource(),
});

export const examplesSource = loader({
  baseUrl: "/docs/examples",
  source: examplesDocs.toFumadocsSource(),
});

export const cookbooksSource = loader({
  baseUrl: "/docs/cookbooks",
  source: cookbooksDocs.toFumadocsSource(),
});
